// Paletas de colores compartidas entre componentes de ruleta

const TEMA_BASE_GREEN = {
  bgPage: 'bg-arena',
  segmento1: '#1F4B3F',
  segmento2: '#3E6B5A',
  linea: '#BFD8B8',
  textoSvg: '#E6DAC6',
  flecha: '#1E2F2A',
  gradiente: 'linear-gradient(135deg, #7FB77E 0%, #3E6B5A 50%, #1F4B3F 100%)',
  bordeInterior: 'bg-beige',
  spinBg: '#1F4B3F',
  spinHover: '#3E6B5A',
  spinBorde: '#7FB77E',
  spinSombra: 'rgba(31, 75, 63, 0.5)',
  spinTexto: 'text-beige',
  resultadoBg: '#1F4B3F',
  resultadoBorde: '#7FB77E',
  resultadoTexto: 'text-beige',
  resultadoTexto2: 'text-lima',
  titulo: 'text-verde-negro',
  tituloSub: 'text-verde-negro/70',
  panel: 'bg-beige',
  panelBorde: 'border-hoja/30',
  panelTitulo: 'text-bosque',
  panelTexto: 'text-verde-negro',
  numeroBg: (i) => i % 2 === 0 ? '#1F4B3F' : '#3E6B5A',
  numeroTexto: 'text-beige',
  legendaItem: 'bg-arena/50',
};

const TEMA_BASE_DOMINGO = {
  bgPage: 'bg-amber-950',
  segmento1: '#78350f',
  segmento2: '#92400e',
  linea: '#fbbf24',
  textoSvg: '#fef3c7',
  flecha: '#451a03',
  gradiente: 'linear-gradient(135deg, #f59e0b 0%, #b45309 50%, #78350f 100%)',
  bordeInterior: 'bg-amber-100',
  spinBg: '#78350f',
  spinHover: '#92400e',
  spinBorde: '#f59e0b',
  spinSombra: 'rgba(120, 53, 15, 0.5)',
  spinTexto: 'text-amber-100',
  resultadoBg: '#78350f',
  resultadoBorde: '#f59e0b',
  resultadoTexto: 'text-amber-100',
  resultadoTexto2: 'text-amber-300',
  titulo: 'text-amber-100',
  tituloSub: 'text-amber-200/70',
  panel: 'bg-amber-900/60',
  panelBorde: 'border-amber-400/30',
  panelTitulo: 'text-amber-200',
  panelTexto: 'text-amber-100',
  numeroBg: (i) => i % 2 === 0 ? '#78350f' : '#92400e',
  numeroTexto: 'text-amber-100',
  legendaItem: 'bg-amber-800/40',
};

export const TEMA_PREMIOS_GREEN = {
  ...TEMA_BASE_GREEN,
  spinDisabled: '#6B8E7D',
  resultadoSubtexto: 'text-beige/70',
  usadoTexto: 'text-verde-negro/60',
  usadoSub: 'text-verde-negro/40',
  terminosTexto: 'text-verde-negro/50',
  terminosHover: 'hover:text-verde-negro/70',
  modalBg: 'bg-beige',
  modalBorde: 'border-hoja/30',
  modalTitulo: 'text-bosque',
  modalTexto: 'text-verde-negro/80',
  modalBullet: 'text-bosque',
  modalBtn: 'bg-bosque text-beige hover:bg-bosque/90',
};

export const TEMA_PREMIOS_DOMINGO = {
  ...TEMA_BASE_DOMINGO,
  spinDisabled: '#a16207',
  resultadoSubtexto: 'text-amber-100/70',
  usadoTexto: 'text-amber-200/60',
  usadoSub: 'text-amber-300/40',
  terminosTexto: 'text-amber-300/50',
  terminosHover: 'hover:text-amber-200/70',
  modalBg: 'bg-amber-900',
  modalBorde: 'border-amber-400/30',
  modalTitulo: 'text-amber-200',
  modalTexto: 'text-amber-100/80',
  modalBullet: 'text-amber-400',
  modalBtn: 'bg-amber-700 text-amber-100 hover:bg-amber-600',
};

export const TEMA_CONSUMO_GREEN = {
  ...TEMA_BASE_GREEN,
  spinDisabled: '#6B8E7D',
  reiniciarBg: '#E6DAC6',
  reiniciarTexto: '#1F4B3F',
  reiniciarBorde: '#7FB77E',
  reiniciarHover: '#BFD8B8',
};

export const TEMA_CONSUMO_DOMINGO = {
  ...TEMA_BASE_DOMINGO,
  spinDisabled: '#a16207',
  reiniciarBg: '#fef3c7',
  reiniciarTexto: '#78350f',
  reiniciarBorde: '#f59e0b',
  reiniciarHover: '#fde68a',
};
